name: Build test

on:
  push:
    branches: [ workflow-tests ]
  pull_request:
    branches: [ workflow-tests ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: famicom-dumper
      PROJECT_PATH: FamicomDumper
      OUTPUT_DIR: output
      CONFIGURATION: Release
    strategy:
      matrix:
        arch: [win-x86, win-x64, win-arm, linux-x64, linux-arm, osx-x64]
        sc: [no-self-contained, self-contained]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dump vars
      if: ${{ matrix.sc == 'self-contained' }}
      env:
        SC_OPS: --self-contained true -p:PublishTrimmed=True
        SC_NAME: -self-contained
      run: echo sc_name $SC_NAME
    - name: Dump vars
      if: ${{ matrix.sc == 'no-self-contained' }}
      env:
        SC_OPS: --no-self-contained
      run: echo sc_name $SC_NAME
    - name: Build
      run: dotnet publish {{ env.PROJECT_PATH }} -c {{ env.CONFIGURATION }} -r {{ matrix.arch }} -p:PublishSingleFile=true {{ env.SC_OPS }} -p:IncludeAllContentForSelfExtract=true -o {{ env.OUTPUT_DIR }}/{{ env.ARCH }}{{ env.SC_NAME }}/{{ env.APP_NAME }}


