name: Build test

on:
  push:
    branches: [ workflow-tests ]
  pull_request:
    branches: [ workflow-tests ]
  workflow_dispatch:

jobs:
  create-release: 
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  publish:
    needs: create-release
    runs-on: ubuntu-latest
    env:
      APP_NAME: famicom-dumper
      PROJECT_PATH: FamicomDumper
      OUTPUT_DIR: output
      CONFIGURATION: Release
    strategy:
      matrix:
        os: [win, linux, osx]
        arch: [x86, x64, arm]
        sc: [no-self-contained, self-contained]
        exclude:
          - os: linux
            arch: x86
          - os: osx
            arch: x86
          - os: osx
            arch: arm          
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dump vars if self-contained
      if: ${{ matrix.sc == 'self-contained' }}
      env:
        SC_OPS: --self-contained true -p:PublishTrimmed=True
        SC_NAME: -self-contained
      run: echo sc_name $SC_NAME
    - name: Dump vars if no-self-contained
      if: ${{ matrix.sc == 'no-self-contained' }}
      env:
        SC_OPS: --no-self-contained
      run: echo SC_OPS $SC_OPS
    - name: Build
      run: dotnet publish $PROJECT_PATH -c $CONFIGURATION -r ${{ matrix.os }}-${{ matrix.arch }} -p:PublishSingleFile=true $SC_OPS -p:IncludeAllContentForSelfExtract=true -o $OUTPUT_DIR/${{ matrix.os }}-${{ matrix.arch }}$SC_NAME/$APP_NAME
    - name: Archive to .tar.gz
      if: ${{ matrix.os != 'win' }}
      env:
        OUTPUT_FILE: famicom-dumper-${{ matrix.os }}-${{ matrix.arch }}$SC_NAME.tar.gz
        MIME: application/tar+gzip
      run: |
        cd $OUTPUT_DIR/${{ matrix.os }}-${{ matrix.arch }}$SC_NAME
        tar -czvf ../../$OUTPUT_FILE $APP_NAME
    - name: Archive to .zip
      if: ${{ matrix.os == 'win' }}
      env:
        OUTPUT_FILE: famicom-dumper-${{ matrix.os }}-${{ matrix.arch }}$SC_NAME.zip
        MIME: application/zip
      run: |
        cd $OUTPUT_DIR/${{ matrix.os }}-${{ matrix.arch }}$SC_NAME
        zip -r9 ../../$OUTPUT_FILE $APP_NAME
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url
    - name: Get Release File Name & Upload URL
      id: get_release_info
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
      run: |
        echo ::set-output name=file_name::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v} # RepositoryName-v1.0.0
        value=`cat release_url/release_url.txt`
        echo ::set-output name=upload_url::$value
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ${{ OUTPUT_FILE }}
        asset_name: ${{ OUTPUT_FILE }}
        asset_content_type: ${{ MIME }}
